# Generated by Django 2.1.2 on 2018-10-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20181008_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='banner_image',
            field=models.BooleanField(default=False),
        ),
    ]
