# Generated by Django 2.1.2 on 2018-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_image_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('FR', 'Featured Image'), ('BR', 'Banner Image'), ('NR', 'Normal Image')], default='NR', max_length=2),
        ),
    ]
