# Generated by Django 2.1.2 on 2018-10-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20181009_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='featured_image',
        ),
    ]
